# version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-webrtc}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-webrtc}
      POSTGRES_DB: ${POSTGRES_DB:-webrtc}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-webrtc}:${POSTGRES_PASSWORD:-webrtc}@db:5432/${POSTGRES_DB:-webrtc}
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data:
